#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  branches:
    develop:
        - step:
            name: build
            caches:
              - node
            script:
              - npm install
              - npm test
              - npm run lint
              - npm run format
        - step:
            name: deploy 
            deployment: test
            # trigger: manual  # Uncomment to make this a manual deployment.
            script:
              - echo "Deploying to test environment"
              - npm run start:prod